-- MySQL Script generated by MySQL Workbench
-- Tue Dec 26 21:36:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Accounting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Accounting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Accounting` DEFAULT CHARACTER SET utf8 ;
USE `Accounting` ;

-- -----------------------------------------------------
-- Table `Accounting`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Accounting`.`Departments` (
  `department_id` INT NOT NULL,
  `department_name` VARCHAR(50) NULL DEFAULT NULL,
  `max_expense_limit` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Accounting`.`ExpenseTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Accounting`.`ExpenseTypes` (
  `expense_type_id` INT NOT NULL,
  `expense_type_name` VARCHAR(50) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `department_id` VARCHAR(45) NULL,
  `monthly_limit` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`expense_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Accounting`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Accounting`.`Employees` (
  `employee_id` INT NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `date_of_birth` VARCHAR(50) NULL DEFAULT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `department_id`),
  INDEX `employees_ibfk_1_idx` (`department_id` ASC) VISIBLE,
  CONSTRAINT `employees_ibfk_1`
    FOREIGN KEY (`department_id`)
    REFERENCES `Accounting`.`Departments` (`department_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Accounting`.`Expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Accounting`.`Expenses` (
  `expense_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `expense_type_id` INT NOT NULL,
  `expense_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`expense_id`, `employee_id`, `expense_type_id`),
  INDEX `expenses_ibfk_1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `expenses_ibfk_2_idx` (`expense_type_id` ASC) VISIBLE,
  CONSTRAINT `expenses_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Accounting`.`Employees` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `expenses_ibfk_2`
    FOREIGN KEY (`expense_type_id`)
    REFERENCES `Accounting`.`ExpenseTypes` (`expense_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
